[theme]
primaryColor = "#0083B8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
maxMessageSize = 200

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true
